### ISSUE TITLE
Function not found: CONTAINS_SUBSTR

### ISSUE THREAD

**Issue by hansottowirtz** [fivetran/dbt-language-server#1125]
It seems like the `CONTAINS_SUBSTR` BigQuery function is missing from this package.

**Comment by pgrivachev** [comment]
Hey @hansottowirtz!

Thank you for creating this issue. You are right, this function [is not a part of ZetaSQL](https://github.com/google/zetasql/issues/135) library that we use. We will add support of this function in the next extension release.

**Comment by pgrivachev** [comment]
Hey @hansottowirtz. I added this function in new version v0.29.0. Please check if it helps. Also please let me know if you have another missing functions.
