### ISSUE TITLE
Go to definition does not go to column when definition is in another file

### ISSUE THREAD

**Issue by SanderRonde** [fivetran/dbt-language-server#1257]
When using go to definition on a column that is defined in another file the extension will currently jump to the top of that file ([see code](https://github.com/fivetran/dbt-language-server/blob/bf2c25dec776bfe43c882805cf69f39e4c0aba08/server/src/definition/SqlDefinitionProvider.ts#L54)). Ideally it would jump to the specific column being defined. I did implement a way around this in [our fork](https://github.com/crispnl/dbt-language-server/pull/2) with some fixes [here](https://github.com/crispnl/dbt-language-server/pull/6) but this way of doing things is very hacky and I'm sure you have a better idea of how to do it within the same data model.

**Comment by pgrivachev** [comment]
Hey, thank you for this example. We have compilation results and parse/analyze results after first project compilation/analysys. I will try to implement this feature.

**Comment by pgrivachev** [comment]
Hey @SanderRonde. I made some changes and now we can go to column definition in external file. After initial project compilation/analysis we can find main select statement in the external file and try to find column definition in this select.

**Comment by SanderRonde** [comment]
Awesome! I tried testing it a bit but found it kind of hard to merge this PR with our fork (which has some fixes for specifically our repo) so I didn't get to testing it. I trust that it works though, and I think this issue can be closed then right?

**Comment by pgrivachev** [comment]
Yes, I will close the issue, but feel free to open a new one if you have any ideas on how to improve extension.
