### ISSUE TITLE
Wizard using incorrect path to python

### ISSUE THREAD

**Issue by thomasaarholt** [fivetran/dbt-language-server#1295]
I keep getting the following error when I open a dbt model:
```
Command failed: "/Users/thomas/oda/dbt-models/.direnv/python-3.11.4" "/Users/thomas/.vscode/extensions/fivetran.dbt-language-server-0.30.2-darwin-arm64/server/python/script.py" 36588 /Users/thomas/oda/dbt-models compile -m +models/logistics_platform/fulfillment_development/inventory/serve/fabrica/fabrica_storage_locations.sql
/bin/sh: /Users/thomas/oda/dbt-models/.direnv/python-3.11.4: is a directory
Wizard for dbt Core (TM)
```
![Screenshot 2023-10-20 at 13 16 59](https://github.com/fivetran/dbt-language-server/assets/2721423/463f8151-027a-4e48-be18-847b703339db)

The correct path is 
`/Users/thomas/oda/dbt-models/.direnv/python-3.11.4/bin/python`
Wizard is using
`/Users/thomas/oda/dbt-models/.direnv/python-3.11.4`

I have searched my VSCode settings, and I can't seem to find anywhere that sets the path incorrectly like this. I've got the following default interpreter path set in both User and Workspace settings.
![image](https://github.com/fivetran/dbt-language-server/assets/2721423/0cc4fb7c-62e3-4164-ba17-b43d563a5756)

When I Cmd + Shift + P "Python: Select Interpreter" and choose the same python instance, I still get the same error.

**Comment by pgrivachev** [comment]
Hey @thomasaarholt,

Thank you for creating this issue. I couldn't reproduce the issue on my side. Wizard extension should use path from the Python extension. Can you please check on your project what is showing as selected interpreter when you open Cmd + Shift + P "Python: Select Interpreter"?
Here is my example:
![image](https://github.com/fivetran/dbt-language-server/assets/3650304/41c6d63d-1847-4e4b-99f2-8b95b9410428)

Also please check the logs from Python Language Server:
![image](https://github.com/fivetran/dbt-language-server/assets/3650304/8cfefc48-d830-43ed-83f9-1c866ef11b94)

**Comment by thomasaarholt** [comment]
Hello again! Sorry for taking so long to get back to you!

Your suggestion was a good one, and there's definitely something funky going on, but it is probably on my end. Here's what I see:
**Select Interpreter**
<img width="880" alt="image" src="https://github.com/fivetran/dbt-language-server/assets/2721423/7af59bff-1863-483b-92e0-9edb07bb025b">

**Python Language Server**
<img width="1657" alt="Screenshot 2023-10-31 at 10 54 09" src="https://github.com/fivetran/dbt-language-server/assets/2721423/220d6335-5cc3-4524-8042-ecb15270132d">

When I open a dbt model, I get asked to install dbt/adapters (dbt-snowflake is installed in the 3.11.4 venv): 
<img width="615" alt="image" src="https://github.com/fivetran/dbt-language-server/assets/2721423/e6f49f58-b745-4315-9711-06cd344276be">

When I press to install, I get the "is a directory" error again, which makes sense.
```
"/Users/thomas/oda/dbt-models/.direnv/python-3.11.4" -m pip install  dbt-core dbt-snowflake
/bin/sh: /Users/thomas/oda/dbt-models/.direnv/python-3.11.4: is a directory
```

**Comment by pgrivachev** [comment]
Hey @thomasaarholt, thank you for clarifications! I was able to reproduce the issue on my side. Working on fix now.

**Comment by pgrivachev** [comment]
@thomasaarholt, I've made some changes in v0.33.0. Could you please check if this helps?

**Comment by thomasaarholt** [comment]
Works perfectly, thank you so much!!
