### ISSUE TITLE
Enable GitHub Discussions

### ISSUE THREAD

**Issue by Gregory108** [fivetran/dbt-language-server#152]
As the title says. [Here](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/enabling-or-disabling-github-discussions-for-a-repository) is documentation.

My actual need is to understand, why for this package it is impossible/impractical to make Windows installation "simple"; or how to make it simple (without WSL and Docker). All other DBT-Bigquery-VSCode extensions I use can work without a "complicated" setup. Together they could have done all the same Wizard package claims to be able to do, but they are dispersed and impossible to tune to work simultaneously (because of fixed file associations). 

Further note: it seems the problem is with `rpc`, which is necessary to query BQ Servers. But [BigQuery Runner minodisk.bigquery-runner](https://marketplace.visualstudio.com/items?itemName=minodisk.bigquery-runner) which extra hustle.

**Comment by Gregory108** [comment]
@pgrivachev, thanks for the reply!

I see `dbt-rpc` (not reliable?) and `ZetaSQL` (not now, but in TBD) are the cause. What unique functionality do they provide that cannot be achieved using Windows-compatible substitutes? It seemed to me that there are packages for everything DBT Wizard provides, but not under one roof (and that causes great friction in a work process)

**Comment by pgrivachev** [comment]
@Gregory108, 

We use `dbt-rpc` to run dbt commands, on Windows we can use dbt CLI for this purpose and we will work on it soon. `ZetaSQL` is used for analyzing SQL query, for highlighting errors in query, for column suggestions and so on.

**Comment by pgrivachev** [comment]
Hey @Gregory108!

We released v0.7.0 which have support Windows but in limited mode without ZetaSQL.

**Comment by Gregory108** [comment]
Hi @pgrivachev!

Thank you so much! You buuuurn! I will test it as soon as I can=)

**Comment by pgrivachev** [comment]
Now we support all functionality for BQ on Windows. It is only requried to install WSL and Ubuntu-20.04 ([updated docs](https://github.com/fivetran/dbt-language-server/blob/main/docs/WindowsSupport.md#windows-support)):
```
wsl --install -d Ubuntu-20.04
```
