### ISSUE TITLE
"Error Highlighting" and "SQL to ref conversion" Not Working for Me

### ISSUE THREAD

**Issue by kyleh-ps** [fivetran/dbt-language-server#482]
Hello, thanks for developing this package!

I think I've downloaded the package properly, since the "Query preview" and "Go to Definition" are working great for me. I was particularly looking forward to SQL syntax errors being highlighted, but no errors are being flagged. I'm probably doing something wrong.

I also don't see the light bulb as shown in the GIF for the "SQL to ref conversion".

**Comment by kyleh-ps** [comment]
I have turned Autosave on as mentioned in the Details section for the package in VS Code Extensions:
![image](https://user-images.githubusercontent.com/90897659/195861147-2ee390f1-2440-4b1b-b53e-875147965ccf.png)

**Comment by pgrivachev** [comment]
Hello @kyleh-ps, 

These features (Error highlighting and SQL to ref conversion) are working only with Big Query destination. Are you using the BigQuery adapter in your dbt project?

**Comment by kyleh-ps** [comment]
@pgrivachev Yes we're using the BigQuery adapter

**Comment by pgrivachev** [comment]
@kyleh-ps, I have prepared a list of questions that will help us resolve the issue.

1. What operating system do you use?
2. Do you see any error from extension when you open your project/dbt model?
3. Can you check the logs of extension and share them ([here is the instruction on how to do this](https://docs.google.com/document/d/e/2PACX-1vQwri6c9d9a4GRQVJR65ur_O_9a9zhY8SZymvZLTgO07ziiypuvC0UCMoO5MIXn61MiTv6DxqqRkzp8/pub))?
4. Do you use default `profiles.yml` location for your project ([dbt docs](https://docs.getdbt.com/docs/get-started/connection-profiles#connecting-to-your-warehouse-using-the-command-line))?

**Comment by kyleh-ps** [comment]
Thanks @pgrivachev, here are my answers:
1. Windows 10 Pro
2. No errors from the extension when I open a dbt project in vscode
3. Please find attached [wfdbt.txt](https://github.com/fivetran/dbt-language-server/files/9801393/wfdbt.txt)
4. I use the profiles.yml file in the `~/.dbt/` project under my user profile, so `C:\Users\KyleHooper\.dbt` . In our company we have multiple dbt repos, so the information for all of the repos is captured in one `profiles.yml` file. Rather than one `profiles.yml` file in each repo.

**Comment by pgrivachev** [comment]
@kyleh-ps, Thank you for your answers
Windows operating system is supported partially and to have all features working it is required to run extension inside docker o WSL ([see docs](https://github.com/fivetran/dbt-language-server/blob/main/docs/WindowsSupport.md)).

But right now we are working on fixing this limitation. And it might be a lot easier to run the extension on Windows soon. I will update this thread once we release this improvement.

**Comment by kyleh-ps** [comment]
Thank you @pgrivachev I'll keep an eye out

**Comment by pgrivachev** [comment]
Hey @kyleh-ps,

We implemented support for all features (including "Error Highlighting" and "SQL to ref conversion") for Windows. The only required thing is installation of WSL and Ubuntu-20.04. We use ubuntu to run ZetaSQL analyzer (because it doesn't support Windows).

So to have "Error Highlighting" and "SQL to ref conversion" working you need to update extension to v0.13.0 and run the following command as Administrator and restart computer ([updated docs](https://github.com/fivetran/dbt-language-server/blob/main/docs/WindowsSupport.md#windows-support)):
```
wsl --install -d Ubuntu-20.04
```

Please let me know if you have any issues with this solution.
