### ISSUE TITLE
Error in installing python package dependencies because of space in file path

### ISSUE THREAD

**Issue by benvitzky** [fivetran/dbt-language-server#489]
Packages installation failed ('C:\Users\David OK\anaconda3\python.exe -m pip install --upgrade dbt-core dbt-redshift'). Reason: Command failed: C:\Users\David OK\anaconda3\python.exe -m pip install --upgrade dbt-core dbt-redshift 'C:\Users\David' is not recognized as an internal or external command, operable program or batch file.

**Comment by pgrivachev** [comment]
Hello,

Thank you for reporting this issue. We are working on fixing bugs in extension on Windows, and this issue will be fixed in the next release.

**Comment by pgrivachev** [comment]
Hey @benvitzky,

We fixed this issue in v0.13.0. Please let me know if it doesn't work.
