### ISSUE TITLE
Does the plugin support dbt v1.3.0?

### ISSUE THREAD

**Issue by jediwarpraptor** [fivetran/dbt-language-server#491]
I'm suddenly having problems with the extension (failed multiple times and then shuts down after 5x failures) and I just upgraded dbt

**Comment by pgrivachev** [comment]
I tried to reproduce the issue with the following configuration but without success, extension works as expected:
```
>/usr/local/bin/python3 -m pip list | grep dbt
dbt-bigquery               1.3.0
dbt-core                   1.3.0
dbt-extractor              0.4.1
dbt-postgres               1.3.0
dbt-rpc                    0.2.0
```

**Comment by jediwarpraptor** [comment]
![image](https://user-images.githubusercontent.com/17027856/196262952-0fa98c4d-a986-45c5-bac8-891583582102.png)

Using the latest it appears.  In addition to upgrading to v1.3 I had also rebuilt the dev container that I run this project in.  I am rebuilding that container again (my original was Ubuntu 20.04, but this new one appears to have taken a default MS dev container OS:  `Linux aeede20265ae 5.10.60.1-microsoft-standard-WSL2 #1 SMP Wed Aug 25 23:20:18 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`)

Will also uninstall/reinstall the plugin to verify.

**Comment by pgrivachev** [comment]
We haven't decided on a fork yet, but we already have support for the dbt CLI and in case when dbt-rpc doesn't work we are using CLI now.

Did you manage to fix the issue with latest version of extension? And why do you think the reason was in `dbt-rpc`?

**Comment by jediwarpraptor** [comment]
Issue with the latest version is fixed, yes.  Sorry should have been more clear.  The only thing I did to get "fix" it was manually update `dbt-rpc` to `0.2.0` - it was at `0.1.2`.  I don't think `pip` even cared about it when I upgraded everything else to `1.3.0`

**Comment by pgrivachev** [comment]
Thank you for clarification! Now it is clear for me how to reproduce the issue.

**Comment by amirbtb** [comment]
Hi folks,
I have similar issues, I am running in a VSCode devcontainer with an ubuntu base image. I am using the version `0.12.2` of the plugin.
Here are the versions of the different dbt packages in my environment :
```
dbt-bigquery             1.3.0
dbt-core                 1.3.0
dbt-extractor            0.4.1
dbt-rpc                  0.2.0
sqlfluff-templater-dbt   1.3.2
```

**Comment by ic-33** [comment]
Hello peeps,
I ran into the following error
```
RPC server failed to compile project, call the "status" method for compile status: Compilation Error in macro generate_database_name (macros/get_custom_name/get_custom_database.sql)
  argument of type 'NoneType' is not iterable
```
I use a VSCode devcontainer with an ubuntu base image as well. The version of the plugin is 0.12.2 . 
Here are the versions of the dbt packages I use:
```
dbt-bigquery             1.3.0
dbt-core                 1.3.0
dbt-extractor            0.4.1
dbt-rpc                  0.2.0
sqlfluff-templater-dbt   1.3.2
```

**Comment by pgrivachev** [comment]
Hello folks @amirbtb, @ic-33, 

Could you please let me know what dev container parameters I should use to reproduce the issue? Also could you share extension logs as explained here: [logs](https://docs.google.com/document/d/e/2PACX-1vQwri6c9d9a4GRQVJR65ur_O_9a9zhY8SZymvZLTgO07ziiypuvC0UCMoO5MIXn61MiTv6DxqqRkzp8/pub)?

**Comment by pgrivachev** [comment]
@amirbtb, @ic-33, I can't reproduce the issue with dbt-core 1.3.0 and dbt-rpc 0.2.0 without additional information. For now you can try to switch compiler to dbt instead of dbt-rpc. You can find this setting in Preferences -> Settings -> Extensions -> Wizard for dbt Core (TM) -> Wizard For Dbt Core(TM): Dbt Compiler

![image](https://user-images.githubusercontent.com/3650304/197772498-f924acfd-28f3-4e18-b87e-f6180600867d.png)

**Comment by ic-33** [comment]
Hello back @pgrivachev and sorry for the absence while.

Here is the information you asked for:

- I use an **ubuntu:20.04** container image.

- The **devcontainer.json** config is as following
```
{
  "name": "dbt development environment",
  "dockerComposeFile": "../docker-compose.yml",
  "service": "dbt_packages",
  "workspaceFolder": "/src",
  "shutdownAction": "stopCompose",
  "extensions": [
	"Fivetran.dbt-language-server"
  ]
}
```

You will also find the extension's logs attached .
[logs_dbt_rpc.txt](https://github.com/fivetran/dbt-language-server/files/9990225/logs_dbt_rpc.txt)

_NB: Please note that the back_project_id envvar works fine within the whole project._

**Comment by pgrivachev** [comment]
@ic-33 we've added support for environment variables in v0.17.0. More details in the issue https://github.com/fivetran/dbt-language-server/issues/604.
