### ISSUE TITLE
Question: Request for clarification between dbt-rpc and dbt-server

### ISSUE THREAD

**Issue by chrisweis** [fivetran/dbt-language-server#681]
Hello,

I see that the FiveTran Wizard for dbt Core requires dbt-rpc which I understand is being deprecated by dbt-server in the second half of 2023.  Curious, is there an option for using the VS Code extension now with dbt-server instead of dbt-rpc?

Thanks!
Chris

**Comment by pgrivachev** [comment]
Hello @chrisweis, 

We recently switched to using dbt CLI by default in [v0.18.0](https://github.com/fivetran/dbt-language-server/releases/tag/v0.18.0). So the extension should work with just dbt installed without dbt-rpc. 

As far as I know dbt-server is not ready for production use and we will investigate the ability to use it in extension once it will be stable.

**Comment by pgrivachev** [comment]
Yes, sorry for inconvenience. We will rework "How to get set up" text.

For Windows you need to install
- dbt and adapters (like `python3 -m pip install dbt-bigquery dbt-rpc`)
- [WSL and Ubuntu](https://github.com/fivetran/dbt-language-server/blob/main/docs/WindowsSupport.md#windows-support) using command `wsl --install -d Ubuntu-20.04`

**Comment by chrisweis** [comment]
No need to apologize, thanks for this great and amazingly quick help!

Confused about one remaining thing: Above you show dbt-rpc being installed, but can we not use dbt CLI instead of dbt-rpc on Windows?

**Comment by pgrivachev** [comment]
>Confused about one remaining thing: Above you show dbt-rpc being installed, but can we not use dbt CLI instead of dbt-rpc on Windows?

No, dbt-rpc has never worked [on Windows](https://github.com/dbt-labs/dbt-rpc/blob/c305bfc6cb1bd5861e364a202ba82804f20528b2/dbt_rpc/task/server.py#L81). Do you have any issue with using dbt CLI on Windows?

**Comment by chrisweis** [comment]
`Do you have any issue with using dbt CLI on Windows?`

Yes, I'm unable to reach the final state of step 6 ("Check that the extension is operating by right-clicking in any .sql model file, and selecting Wizard for dbt Core (TM) > Show query preview.").  My status:
- Installed the VS Code extension (v 0.18.0), WSL is enabled per the instructions
- Using a dbt-snowflake project (in a Python virtual environment with default dbt YML locations)
- There is no "Preview icon in the top right corner" and no "Right click > Wizard for dbt Core (TM)"
- The only Wizard command palette items that does anything seems to be the "Show query preview" (but it only opens the preview pane, doesn't actually preview anything).

Thanks for any further help you can offer

**Comment by pgrivachev** [comment]
This is weird. Extension should be activated if dbt_project.yml exists and if you open any sql model with `sql`, `jinja-sql` or `sql-bigquery` language mode as shown in the following screenshot:
![image](https://user-images.githubusercontent.com/3650304/212397629-8dabb011-e98b-4868-8d76-2b500427b179.png)

Could you please look at logs from `Output` tab as described here  https://docs.google.com/document/d/e/2PACX-1vQwri6c9d9a4GRQVJR65ur_O_9a9zhY8SZymvZLTgO07ziiypuvC0UCMoO5MIXn61MiTv6DxqqRkzp8/pub and attach them here if it is possible?

**Comment by chrisweis** [comment]
Logs:
```
Client 2023-01-13T19:15:13.716Z: Wizard for dbt Core (TM) version: 0.18.0
/ 2023-01-13T19:15:14.003Z:  Starting server without project
/ 2023-01-13T19:15:14.045Z:  Process '"C:\Dev-Envs\dbt-env\Scripts\python.exe" -c "import dbt_rpc.__main__; dbt_rpc.__main__.main(['--version'])"' exited with code 1
/ 2023-01-13T19:15:16.388Z:  Process '"C:\Dev-Envs\dbt-env\Scripts\python.exe" -c "import dbt.main; dbt.main.main(['--version'])"' exited with code 0
/ 2023-01-13T19:15:16.388Z:  dbtPythonVersion = 1.3.2 
```
Seems like it's trying to run dbt_rpc?

**Comment by pgrivachev** [comment]
I have one assumption that `snowflake.snowflake-vsc` extension overrides Language Mode for .sql files to their specific `snowflake-sql`. You can try to [reassign Language Mode](https://code.visualstudio.com/docs/languages/overview#_changing-the-language-for-the-selected-file) of .sql files to `sql`
![image](https://user-images.githubusercontent.com/3650304/212409135-7790c6a5-f130-4ec9-adeb-985e5e8e478d.png)

Probably after that extension will start working.

The other limitation now it that error highlighting, auto-completion of columns, tables, and function signature help are only available for BigQuery destination. But we now actively working on Snowflake destination support.
