### ISSUE TITLE
Encountered an error: Parsing Error   Env var required but not provided: '<env_var>'

### ISSUE THREAD

**Issue by assafshayhaimhibob** [fivetran/dbt-language-server#684]
Hi,
Seems like it doesn't work with profiles.yml env_vars.
![Xnip2023-01-19_20-35-49](https://user-images.githubusercontent.com/110016980/213531304-5540fc04-5805-4683-9800-ccbd33c7de26.jpg)
![Xnip2023-01-19_20-37-05](https://user-images.githubusercontent.com/110016980/213531329-293dcabb-e814-4bdf-94b5-d75eeddf2057.jpg)

**Comment by pgrivachev** [comment]
Hello,

If you set variable in shell, you probably need to run VS Code from this shell using `code <project path>` command and then extension should see the variable. To be able to use `code` command in your shell press `CMD + SHIFT + P` in VS Code, type shell command and select Install code command in path.

Please let me know if this solution works.

**Comment by assafshayhaimhibob** [comment]
I set the vars in .zshenv.
When I execute dbt debug/run it works fine.
The only problem is in the IDE

**Comment by assafshayhaimhibob** [comment]
I restarted VSCode and it seems to be working now. thank you!
