### ISSUE TITLE
Error: No connection established

### ISSUE THREAD

**Issue by wtfzambo** [fivetran/dbt-language-server#890]
Hello, first of all thanks for this extension.

It seems that I can't manage to make it connect to my BQ instance to take advantage of autocompletion and the like.

This is the full stack-trace.

<details>

<summary>Stack trace</summary>

```sh

Client 2023-04-25T10:31:29.819Z: Wizard for dbt Core (TM) version: 0.22.0
Client 2023-04-25T10:31:30.928Z: Client /home/wtfzambo/my-stuff/projects/repos/de_zoomcamp_project/dbt switched from Stopped to Starting state
 2023-04-25T10:31:31.556Z:  Starting server without project
dbt 2023-04-25T10:31:31.782Z:  Profile name found: data_engineering_subreddit
dbt 2023-04-25T10:31:31.785Z:  Starting server for folder /home/wtfzambo/my-stuff/projects/repos/de_zoomcamp_project/dbt.
dbt 2023-04-25T10:31:31.793Z:  manifest.json was successfully parsed
dbt 2023-04-25T10:31:31.793Z:  models, macros, sources were successfully updated
Client 2023-04-25T10:31:31.852Z: Client /home/wtfzambo/my-stuff/projects/repos/de_zoomcamp_project/dbt switched from Starting to Running state
dbt 2023-04-25T10:31:31.859Z:  Profile name found: data_engineering_subreddit
dbt 2023-04-25T10:31:32.015Z:  Process '"/home/wtfzambo/my-stuff/projects/repos/de_zoomcamp_project/.venv/bin/python" -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"' exited with code 0
dbt 2023-04-25T10:31:32.696Z:  Starting zetasql on port 56438
dbt 2023-04-25T10:31:34.867Z:  Error: Worker stopped due to error Error: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /home/wtfzambo/.vscode-server/extensions/fivetran.dbt-language-server-0.22.0-linux-x64/server/node_modules/ffi-napi/build/Release/ffi_bindings.node)
    at Worker.<anonymous> (/home/wtfzambo/.vscode-server/extensions/fivetran.dbt-language-server-0.22.0-linux-x64/server/out/webpack:/dbt-language-server/node_modules/@fivetrandevelopers/zetasql/lib/server.js:11:44)
    at Worker.emit (node:events:526:28)
    at Worker.emit (node:domain:475:12)
    at Worker.[kOnErrorMessage] (node:internal/worker:289:10)
    at Worker.[kOnMessage] (node:internal/worker:300:37)
    at MessagePort.<anonymous> (node:internal/worker:201:57)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:647:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
    at Worker.[kOnExit] (node:internal/worker:267:5)
    at Worker.<computed>.onexit (node:internal/worker:198:20)
 2023-04-25T10:31:36.847Z:  Process '"/home/wtfzambo/my-stuff/projects/repos/de_zoomcamp_project/.venv/bin/python" -c "import dbt.main; dbt.main.main(['--profiles-dir','/home/wtfzambo/.dbt','--version'])"' exited with code 0
 2023-04-25T10:31:36.848Z:  dbtPythonVersion = 1.4.6 
dbt 2023-04-25T10:31:37.474Z:  Process 'dbt --profiles-dir /home/wtfzambo/my-stuff/projects/repos/de_zoomcamp_project/dbt --version' exited with code 0
dbt 2023-04-25T10:31:37.495Z:  Process '"/home/wtfzambo/my-stuff/projects/repos/de_zoomcamp_project/.venv/bin/python" -c "import dbt.main; dbt.main.main(['--profiles-dir','/home/wtfzambo/my-stuff/projects/repos/de_zoomcamp_project/dbt','--version'])"' exited with code 0
dbt 2023-04-25T10:31:37.496Z:  dbtPythonVersion = 1.4.6 dbtGlobalVersion = 1.4.6 
dbt 2023-04-25T10:31:38.982Z:  manifest.json was successfully parsed
dbt 2023-04-25T10:31:42.152Z:  manifest.json was successfully parsed
dbt 2023-04-25T10:31:42.152Z:  models, macros, sources were successfully updated
dbt 2023-04-25T10:31:42.424Z:  Starting to recompile/reanalyze the project
dbt 2023-04-25T10:31:42.425Z:  Starting project compilation
dbt 2023-04-25T10:31:42.438Z:  {"dbtVersion":"1.4.6","pythonPath":"\"/home/wtfzambo/my-stuff/projects/repos/de_zoomcamp_project/.venv/bin/python\"","pythonVersion":"3.11.1","initTime":"10653.057929001749","type":"bigquery","method":"service-account","winWsl":"false"}
dbt 2023-04-25T10:31:42.670Z:  Process '"/home/wtfzambo/my-stuff/projects/repos/de_zoomcamp_project/.venv/bin/python" -c "import dbt.main; dbt.main.main(['--profiles-dir','/home/wtfzambo/my-stuff/projects/repos/de_zoomcamp_project/dbt','--no-anonymous-usage-stats','--no-use-colors','compile','-m','+models/base/subreddit_data_raw/base_subreddit_data_raw__submissions.sql'])"' exited with code 0
dbt 2023-04-25T10:31:42.674Z:  manifest.json was successfully parsed
dbt 2023-04-25T10:31:42.675Z:  models, macros, sources were successfully updated
dbt 2023-04-25T10:31:42.816Z:  Error: 14 UNAVAILABLE: No connection established

```

</details>

It may be related to [this other issue](https://github.com/microsoft/vscode/issues/180629)

**Comment by pgrivachev** [comment]
Hello @wtfzambo, 

Thank you for creating this bug report. Could you please clarify which operating system you are using? Additionally, are you utilizing a Docker container to run the extension?

**Comment by wtfzambo** [comment]
@pgrivachev pardon my imprecision.

I'm running on WSL2 with Ubuntu 20.04 and the project is not running in a Docker container.

Also, I tried a bunch of things:

- Different profile settings (both under the project folder as well as in `~/.dbt/`
- With and without env variables in `profile.yml` (thought they could be the reason of failed connection
- Disabling dbt Power User extension (maybe it created some conflicts)

For the record, dbt Power User does pick up the profile info and is able to show me a query preview and run models through the quick button.

**Comment by pgrivachev** [comment]
Thank you for clarification. I was able to reproduce issue on my side.

As a workaround you could try to run extension on Windows side and use [Ubuntu WSL only for ZetaSQL](https://github.com/fivetran/dbt-language-server/blob/main/docs/WindowsSupport.md#windows-support).

**Comment by pgrivachev** [comment]
Looks like we have this issue also for docker environment. I will update this thread once I fix the issue and publish new extension version.

**Comment by pgrivachev** [comment]
Hey @wtfzambo, I published version 0.23.0 with fix.

Could you please try it on WSL and let me know if it starts working?

**Comment by wtfzambo** [comment]
Fantastic, yes it works now with the column validation:

<img src="https://user-images.githubusercontent.com/47462792/234881334-22e19e79-6588-43a9-ab36-5055a37ab218.png" width=60%>

I have one observation and two questions:

- Function `ML.ROBUST_SCALER` seems to be missing
<img src="https://user-images.githubusercontent.com/47462792/234881541-2f7746c8-c31c-4ca4-ad7a-7f1c943e1bc0.png" width=70%>

- Is it possible to disable a warning for a specific row (e.g. like `-- noqa`) ?

- How do I enable autosuggest for the columns? Is there a specific VSCode setting that I need to turn on? Right now I see the BQ functions being suggested in the tooltip, but not the cols. See screen:
<img src="https://user-images.githubusercontent.com/47462792/234882490-a57f58e6-20a9-4a24-9d1a-0f433fa95ae5.png" width=70%>

**Comment by pgrivachev** [comment]
> * Function `ML.ROBUST_SCALER` seems to be missing

It is known issue, currently [ZetaSQL doesn't support these functions](https://github.com/google/zetasql/issues/14). Are you utilizing these functions in your dbt project? If so, I can attempt to add support myself.

> * Is it possible to disable a warning for a specific row (e.g. like `-- noqa`) ?

At the moment, we do not offer the ability to disable warnings/errors.

> * How do I enable autosuggest for the columns? Is there a specific VSCode setting that I need to turn on? Right now I see the BQ functions being suggested in the tooltip, but not the cols. See screen:

The autosuggest feature for columns relies on context and may not be highly intuitive. I've provided a GIF example to illustrate its functionality. When there's compilable SQL, the feature can suggest columns; otherwise, it cannot. If you have a query with context and the extension does not suggest columns, it may be a bug.
![completions](https://user-images.githubusercontent.com/3650304/235134398-6e2ec8f7-7b8d-4623-8b5c-1d5ab2ab44c2.gif)

**Comment by wtfzambo** [comment]
Hey @pgrivachev , sorry for the late reply.

Trying to recreate your example, I can confirm that it does work, but it struggles, as it takes quite a bit of time before being able to show the column suggestions.

I don't know if this is expected or if it's a behavior you're not experiencing.

**Comment by wtfzambo** [comment]
Thanks for the quick reply @pgrivachev .

I tried with a couple of tables, one had only 3 columns, another has about 20.

In both cases it was slow to pick up the suggestions, and if switching one table for another in the same `.sql` file, it would keep suggesting the old columns for a while.

I can make a gif if needed.

**Comment by pgrivachev** [comment]
@wtfzambo, thank you for this detailed description.

Please make git if it is possible.

**Comment by wtfzambo** [comment]
Hey @pgrivachev , sorry for the late reply, I had completely missed the notification.

Here's what I noticed: the column suggestion seems to work only when the `sql` file being worked on can be compiled properly without errors at least once. See what I mean in the following gif:

<p align="center">
<img src="https://github.com/fivetran/dbt-language-server/assets/47462792/39375a91-ebb3-4620-bddb-2e1618452cc1" width=80%>
</p>

Also, it seems that the column autosuggestion isn't able to work in CTEs, see next gif:

<p align="center">
<img src="https://github.com/fivetran/dbt-language-server/assets/47462792/79bef6e5-b500-4c58-a0c3-14bfc474f719" width=80%>
</p>

**Comment by pgrivachev** [comment]
Since v0.31.0 autosuggestion should work in CTEs. Ml functions are not supported on ZetaSQL side. Once the team supports these type of functions we will add them to the extension.
