### ISSUE TITLE
`_FILE_NAME` pseudo column not recognized

### ISSUE THREAD

**Issue by ciscodebs** [fivetran/dbt-language-server#942]
Use of `_FILE_NAME` pseudo column is not a recognized name by dbt wizard resulting in a reported error.

[Official Google Cloud Docs](https://cloud.google.com/bigquery/docs/query-cloud-storage-data#query_the_file_name_pseudo-column)

Screenshot
<img width="471" alt="image" src="https://github.com/fivetran/dbt-language-server/assets/315974/28f48091-eef1-480a-b439-c0319ab37164">

P.S. Thanks for the extension. I'm a huge fan!

**Comment by pgrivachev** [comment]
Hey, thank you for this bug report. I will start working on this soon.

**Comment by ciscodebs** [comment]
You rock! Keep up the great work :)

**Comment by ciscodebs** [comment]
Resolved! Thanks @pgrivachev
